version: '3.8'
services:
################# POSTGRESQL - DATABASE ###################
  db:
    image: postgres:latest
    container_name: db_container
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - matcha_network
    volumes:
      - database:/var/lib/postgresql/data
################# PYTHON FLASK - BACKEND ##################
  back:
    image: flask_img
    build:
      context: ./back
    container_name: flask_container
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on: 
      - db
    env_file:
      - .env
    networks:
      - matcha_network
    volumes:
      - ./back:/app
################# TYPESCRIPT REACT - FRONTEND #############
  front:
    image: reactjs_img
    build:
      context: ./front
    container_name: react_container
    restart: always
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - matcha_network
    env_file:
      - .env
    volumes:
      - ./front:/dev/app/
######################### ADMINER ##########################
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db_container
    ports:
      - 8080:8080
    networks:
      - matcha_network
volumes:
  database:
networks:
  matcha_network:
    driver: bridge